dubbo:
  registry:
    address: zookeeper://192.168.121.150:2181
  scan:
    base-packages:
      com.tjetc.service
  provider: 
    application:
      oneplus_provider
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl 
    username: nobug
    password: 123456

